// Globals set by running an initializer section on code load

import "Imports.cls"

import (r32) Testit()

i32 a = 1

RGB red

[Entry]
export (bool) test()
   func2()
   return a == 1 && real == 0.5 && square == 16 && arr[2][3] == 5


type RGB
   r32 r,g,b

// not yet implemented [TestAttribute "testing"]   
i32 arr[3][4]

r32 real = 0.5 
   
[E2]
[E3]
() func2()
   for i in 0..2
      for j in 0..3
         arr[i][j] = i+j
   return
   

i32 square = Square(4)

(i32) Square(i32 value)
   return value*value
   