() func()
   i32 a,b,c = 1,2,3
   a,b,c += 2,3,4

/*i32 g = 1
r32 b = 1.0

type myType 
   i32 v1,v2

[Entry]
(i32) total(i32 p)
    i32 loc = 0
    myType t
    //t.v1 = 0
    //t.v2 = 1
    for i in 1..10
       // pass in constant, local, parameter, global, expression, type
       loc = 0 //func(1,i,loc,p,g,i-loc*2,t)
    return loc
    
(i32) func(i32 p1, i32 p2, i32 p3, i32 p4, i32 p5, i32 p6, myType p7)
   i32 v = 0//p1+p2+p3+p4+p5+p6
   return v*v
*/   